name: EchoBoxClanSystem
version: '2_0.1'
author: sorryplspls
main: me.liam.echoBoxClanSystem.Main
api-version: '1.20'
softdepend: [ PlaceholderAPI ]


commands:
  clanchat:
  claninvite:
  clanaccept:
  clanchest:
  claninfo:
  clanmanagement:
  clanadmin:
  clan:
    aliases: [ clans, c ]